# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .azure_blob_folder import *
from .google_cloud_folder import *
from .provider import *
from .s3_bucket_folder import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "synced-folder",
  "mod": "index",
  "fqn": "pulumi_synced_folder",
  "classes": {
   "synced-folder:index:AzureBlobFolder": "AzureBlobFolder",
   "synced-folder:index:GoogleCloudFolder": "GoogleCloudFolder",
   "synced-folder:index:S3BucketFolder": "S3BucketFolder"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "synced-folder",
  "token": "pulumi:providers:synced-folder",
  "fqn": "pulumi_synced_folder",
  "class": "Provider"
 }
]
"""
)
