// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SyncedFolder
{
    [SyncedFolderResourceType("synced-folder:index:AzureBlobFolder")]
    public partial class AzureBlobFolder : Pulumi.ComponentResource
    {
        /// <summary>
        /// Create a AzureBlobFolder resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AzureBlobFolder(string name, AzureBlobFolderArgs args, ComponentResourceOptions? options = null)
            : base("synced-folder:index:AzureBlobFolder", name, args ?? new AzureBlobFolderArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class AzureBlobFolderArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the Azure storage container to sync to. Required.
        /// </summary>
        [Input("containerName", required: true)]
        public Input<string> ContainerName { get; set; } = null!;

        /// <summary>
        /// Whether to have Pulumi manage files as individual cloud resources. Defaults to `true`.
        /// </summary>
        [Input("managedObjects")]
        public Input<bool>? ManagedObjects { get; set; }

        /// <summary>
        /// The path (relative or fully-qualified) to the folder containing the files to be synced. Required.
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        /// <summary>
        /// The name of the Azure resource group that the storage account belongs to. Required.
        /// </summary>
        [Input("resourceGroupName", required: true)]
        public Input<string> ResourceGroupName { get; set; } = null!;

        /// <summary>
        /// The name of the Azure storage account that the container belongs to. Required.
        /// </summary>
        [Input("storageAccountName", required: true)]
        public Input<string> StorageAccountName { get; set; } = null!;

        public AzureBlobFolderArgs()
        {
        }
    }
}
