// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SyncedFolder
{
    [SyncedFolderResourceType("synced-folder:index:S3BucketFolder")]
    public partial class S3BucketFolder : Pulumi.ComponentResource
    {
        /// <summary>
        /// The AWS S3 permissions to apply to synced objects.
        /// </summary>
        [Output("acl")]
        public Output<string> Acl { get; private set; } = null!;

        /// <summary>
        /// The name of the cloud storage bucket to sync to.
        /// </summary>
        [Output("bucketName")]
        public Output<string> BucketName { get; private set; } = null!;

        /// <summary>
        /// Whether to track individual bucket objects with Pulumi. Default is true.
        /// </summary>
        [Output("manageObjects")]
        public Output<bool> ManageObjects { get; private set; } = null!;

        /// <summary>
        /// The relative path to the folder you want to sync from.
        /// </summary>
        [Output("path")]
        public Output<string> Path { get; private set; } = null!;


        /// <summary>
        /// Create a S3BucketFolder resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public S3BucketFolder(string name, S3BucketFolderArgs args, ComponentResourceOptions? options = null)
            : base("synced-folder:index:S3BucketFolder", name, args ?? new S3BucketFolderArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class S3BucketFolderArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The AWS S3 permissions to apply to synced objects.
        /// </summary>
        [Input("acl", required: true)]
        public Input<string> Acl { get; set; } = null!;

        /// <summary>
        /// The name of the cloud storage bucket to sync to.
        /// </summary>
        [Input("bucketName", required: true)]
        public Input<string> BucketName { get; set; } = null!;

        /// <summary>
        /// Whether to track individual bucket objects with Pulumi. Default is true.
        /// </summary>
        [Input("manageObjects")]
        public Input<bool>? ManageObjects { get; set; }

        /// <summary>
        /// The relative path to the folder you want to sync from.
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        public S3BucketFolderArgs()
        {
        }
    }
}
