// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SyncedFolder
{
    [SyncedFolderResourceType("synced-folder:index:S3BucketFolder")]
    public partial class S3BucketFolder : Pulumi.ComponentResource
    {
        /// <summary>
        /// Create a S3BucketFolder resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public S3BucketFolder(string name, S3BucketFolderArgs args, ComponentResourceOptions? options = null)
            : base("synced-folder:index:S3BucketFolder", name, args ?? new S3BucketFolderArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class S3BucketFolderArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The AWS [Canned ACL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl) to apply to each file (e.g., `public-read`). Required.
        /// </summary>
        [Input("acl", required: true)]
        public Input<string> Acl { get; set; } = null!;

        /// <summary>
        /// The name of the S3 bucket to sync to (e.g., `my-bucket` in `s3://my-bucket`). Required.
        /// </summary>
        [Input("bucketName", required: true)]
        public Input<string> BucketName { get; set; } = null!;

        /// <summary>
        /// Disables adding an [alias](https://www.pulumi.com/docs/intro/concepts/resources/options/aliases/) resource option to managed objects in the bucket.
        /// </summary>
        [Input("disableManagedObjectAliases")]
        public Input<bool>? DisableManagedObjectAliases { get; set; }

        /// <summary>
        /// Include hidden files ("dotfiles") when synchronixing folders. False by default.
        /// </summary>
        [Input("includeHiddenFiles")]
        public Input<bool>? IncludeHiddenFiles { get; set; }

        /// <summary>
        /// Whether to have Pulumi manage files as individual cloud resources. Defaults to `true`.
        /// </summary>
        [Input("managedObjects")]
        public Input<bool>? ManagedObjects { get; set; }

        /// <summary>
        /// The path (relative or fully-qualified) to the folder containing the files to be synced. Required.
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        public S3BucketFolderArgs()
        {
        }
    }
}
