// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package syncedfolder

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-synced-folder/sdk/go/synced-folder/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "synced-folder:index:AzureBlobFolder":
		r = &AzureBlobFolder{}
	case "synced-folder:index:GoogleCloudFolder":
		r = &GoogleCloudFolder{}
	case "synced-folder:index:S3BucketFolder":
		r = &S3BucketFolder{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:synced-folder" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"synced-folder",
		"index",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"synced-folder",
		&pkg{version},
	)
}
