// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class S3BucketFolder extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'synced-folder:index:S3BucketFolder';

    /**
     * Returns true if the given object is an instance of S3BucketFolder.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is S3BucketFolder {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === S3BucketFolder.__pulumiType;
    }


    /**
     * Create a S3BucketFolder resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: S3BucketFolderArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.acl === undefined) && !opts.urn) {
                throw new Error("Missing required property 'acl'");
            }
            if ((!args || args.bucketName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'bucketName'");
            }
            if ((!args || args.path === undefined) && !opts.urn) {
                throw new Error("Missing required property 'path'");
            }
            resourceInputs["acl"] = args ? args.acl : undefined;
            resourceInputs["bucketName"] = args ? args.bucketName : undefined;
            resourceInputs["disableManagedObjectAliases"] = args ? args.disableManagedObjectAliases : undefined;
            resourceInputs["includeHiddenFiles"] = args ? args.includeHiddenFiles : undefined;
            resourceInputs["managedObjects"] = args ? args.managedObjects : undefined;
            resourceInputs["path"] = args ? args.path : undefined;
        } else {
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(S3BucketFolder.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a S3BucketFolder resource.
 */
export interface S3BucketFolderArgs {
    /**
     * The AWS [Canned ACL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl) to apply to each file (e.g., `public-read`). Required.
     */
    acl: pulumi.Input<string>;
    /**
     * The name of the S3 bucket to sync to (e.g., `my-bucket` in `s3://my-bucket`). Required.
     */
    bucketName: pulumi.Input<string>;
    /**
     * Disables adding an [alias](https://www.pulumi.com/docs/intro/concepts/resources/options/aliases/) resource option to managed objects in the bucket.
     */
    disableManagedObjectAliases?: pulumi.Input<boolean>;
    /**
     * Include hidden files ("dotfiles") when synchronixing folders. False by default.
     */
    includeHiddenFiles?: pulumi.Input<boolean>;
    /**
     * Whether to have Pulumi manage files as individual cloud resources. Defaults to `true`.
     */
    managedObjects?: pulumi.Input<boolean>;
    /**
     * The path (relative or fully-qualified) to the folder containing the files to be synced. Required.
     */
    path: pulumi.Input<string>;
}
