// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class S3BucketFolder extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'synced-folder:index:S3BucketFolder';

    /**
     * Returns true if the given object is an instance of S3BucketFolder.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is S3BucketFolder {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === S3BucketFolder.__pulumiType;
    }

    /**
     * The AWS S3 permissions to apply to synced objects.
     */
    public readonly acl!: pulumi.Output<string>;
    /**
     * The name of the cloud storage bucket to sync to.
     */
    public readonly bucketName!: pulumi.Output<string>;
    /**
     * Whether to track individual bucket objects with Pulumi. Default is true.
     */
    public readonly manageObjects!: pulumi.Output<boolean>;
    /**
     * The relative path to the folder you want to sync from.
     */
    public readonly path!: pulumi.Output<string>;

    /**
     * Create a S3BucketFolder resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: S3BucketFolderArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.acl === undefined) && !opts.urn) {
                throw new Error("Missing required property 'acl'");
            }
            if ((!args || args.bucketName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'bucketName'");
            }
            if ((!args || args.path === undefined) && !opts.urn) {
                throw new Error("Missing required property 'path'");
            }
            resourceInputs["acl"] = args ? args.acl : undefined;
            resourceInputs["bucketName"] = args ? args.bucketName : undefined;
            resourceInputs["manageObjects"] = args ? args.manageObjects : undefined;
            resourceInputs["path"] = args ? args.path : undefined;
        } else {
            resourceInputs["acl"] = undefined /*out*/;
            resourceInputs["bucketName"] = undefined /*out*/;
            resourceInputs["manageObjects"] = undefined /*out*/;
            resourceInputs["path"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(S3BucketFolder.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a S3BucketFolder resource.
 */
export interface S3BucketFolderArgs {
    /**
     * The AWS S3 permissions to apply to synced objects.
     */
    acl: pulumi.Input<string>;
    /**
     * The name of the cloud storage bucket to sync to.
     */
    bucketName: pulumi.Input<string>;
    /**
     * Whether to track individual bucket objects with Pulumi. Default is true.
     */
    manageObjects?: pulumi.Input<boolean>;
    /**
     * The relative path to the folder you want to sync from.
     */
    path: pulumi.Input<string>;
}
